[book]
authors = ["Kurt Pan"]
language = "en"
multilingual = false
src = "src"
title = "密碼龐克倫理"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
marker = "[TOC]"
max-level = 4

[preprocessor.katex]
after = ["links"]

[output.html]
theme = "theme"
additional-css = ["theme/custom-fonts.css"]

[output.html.search]
enable = false

[output.html.print]
enable = false

[output.html.fold]
enable = true   # whether or not to enable section folding
level = 0        # the depth to start folding